[package]
name = "mos6502"
edition = "2021"
description = "An emulator for the MOS Technology 6502 made for learning purposes"
readme = "README.md"
license = "MIT"
keywords = ["emulator", "6502"]

[dependencies]
num_enum = "0.7.2"
